# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "trusty32"
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-i386-vagrant-disk1.box"
  config.vm.host_name = "prof-trusty32"
  config.vm.network :private_network, ip: "192.168.10.100"
  config.vm.provision "shell", path: "../../provisioning/prof-install.sh"
end
