# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos_7_64"
  config.vm.box_url = "https://github.com/holms/vagrant-centos7-box/releases/download/7.1.1503.001/CentOS-7.1.1503-x86_64-netboot.box"
  config.vm.host_name = "prof-centos-7-64"
  config.vm.provision "file", source: "../../provisioning/errhandler.sh", destination: "/tmp/errhandler.sh"
  config.vm.provision "file", source: "../../provisioning/libstrophe.sh", destination: "/tmp/libstrophe.sh"
  config.vm.provision "file", source: "../../provisioning/cmocka.sh", destination: "/tmp/cmocka.sh"
  config.vm.provision "file", source: "../../provisioning/profanity.sh", destination: "/tmp/profanity.sh"
  config.vm.provision "shell", path: "../provisioning/prof-install.sh"
end
