# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "opensuse_12_3_64"
  config.vm.box_url = "http://sourceforge.net/projects/opensusevagrant/files/12.3/opensuse-12.3-64.box/download"
  config.vm.host_name = "prof-opensuse12-3-64"
  config.vm.provision "file", source: "../../provisioning/errhandler.sh", destination: "/tmp/errhandler.sh"
  config.vm.provision "file", source: "../../provisioning/libstrophe.sh", destination: "/tmp/libstrophe.sh"
  config.vm.provision "file", source: "../../provisioning/cmocka.sh", destination: "/tmp/cmocka.sh"
  config.vm.provision "file", source: "../../provisioning/profanity.sh", destination: "/tmp/profanity.sh"
  config.vm.provision "shell", path: "../provisioning/prof-install.sh"
end
