# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "fedora_19_64"
  config.vm.box_url = "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_fedora-19_chef-provisionerless.box"
  config.vm.host_name = "prof-fedora-19-64"
  config.vm.provision "file", source: "../../provisioning/errhandler.sh", destination: "/tmp/errhandler.sh"
  config.vm.provision "file", source: "../../provisioning/libstrophe.sh", destination: "/tmp/libstrophe.sh"
  config.vm.provision "file", source: "../../provisioning/cmocka.sh", destination: "/tmp/cmocka.sh"
  config.vm.provision "file", source: "../../provisioning/profanity.sh", destination: "/tmp/profanity.sh"
  config.vm.provision "shell", path: "../provisioning/prof-install.sh"
end
